#!/bin/sh

PATH=`pwd`:$PATH

for i in `cat ../package/commands` `grep -v nossl <command.ssl || :`; do
  echo "Creating new $i.dist..."
  env - PATH="$PATH" ctmp="`pwd`/check-tmp" $i.check 2>&1 |cat -v >$i.dist
done
