#
# build haproxy and stunnel
#
# dronnikov@gmail.com 2011
#

HAPROXY=haproxy-1.5-dev6
STUNNEL=stunnel-4.38
ZEROMQ=zeromq-2.1.7

all: bin lib

bin: $(HAPROXY)/haproxy $(STUNNEL)/src/stunnel
	strip -s -o haproxy $(HAPROXY)/haproxy
	strip -s -o stunnel $(STUNNEL)/src/stunnel

lib: $(ZEROMQ)/src/.libs/libzmq.a

$(HAPROXY)/haproxy: $(HAPROXY)
	make -C $^ TARGET=linux26

$(HAPROXY): $(HAPROXY).tar.gz
	tar xzpf $^

$(HAPROXY).tar.gz:
	wget http://haproxy.1wt.eu/download/1.5/src/devel/$(HAPROXY).tar.gz

$(STUNNEL)/src/stunnel: $(STUNNEL)
	dpkg -s libssl-dev
	(cd $(STUNNEL) ; ./configure )
	make -C $^

$(STUNNEL): $(STUNNEL).tar.gz
	tar xzpf $^
	(cd $@ ; patch -Np1 < ../$(STUNNEL)-sendproxy.diff >1 2>2)

$(STUNNEL).tar.gz:
	wget http://ftp.nluug.nl/pub/networking/stunnel/$(STUNNEL).tar.gz

$(ZEROMQ)/src/.libs/libzmq.a: $(ZEROMQ)
	dpkg -s uuid-dev
	( cd $^; ./configure --prefix=/usr )
	make -C $^

$(ZEROMQ): $(ZEROMQ).tar.gz
	tar xzpf $^

$(ZEROMQ).tar.gz:
	wget http://download.zeromq.org/$(ZEROMQ).tar.gz

install: bin lib
	dpkg -s haproxy
	dpkg -s stunnel4
	make -C $(ZEROMQ) install
	ldconfig
	-cp haproxy /usr/sbin
	-rm /usr/bin/stunnel stunnel3 stunnel4
	-cp stunnel /usr/bin
	-mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
	cp haproxy.cfg /etc/haproxy/haproxy.cfg
	-mv /etc/stunnel/stunnel.conf /etc/stunnel/stunnel.conf.orig
	cp stunnel.conf /etc/stunnel
	cp cert.pem /etc/stunnel/farm-cert.pem
	cp key.pem /etc/stunnel/farm-key.pem

uninstall:
	rm /usr/local/bin/haproxy /usr/local/bin/stunnel

clean:
	rm -fr haproxy stunnel $(HAPROXY) $(STUNNEL) $(ZEROMQ)

distclean: clean
	rm -fr $(HAPROXY).tar.gz $(STUNNEL).tar.gz $(ZEROMQ).tar.gz

.PHONY: all bin lib install uninstall clean distclean
